@echo off
echo gen cs ...
python gen_cs.py
echo gen go ...
python gen_go.py
echo gen json ...
python gen_json.py
echo copy data to server path ...
copy ..\JekoClient\GameClient\JekoClient\Assets\Resources\Config\ConfigData\*.json ..\JekoServer\config_data\json
echo finish!
pause